edition = "2018"
max_width = 80
tab_spaces = 4
hard_tabs = true
#indent_style = "Block"

#format_strings = true
#format_code_in_doc_comments = true

# imports
#imports_granularity = "Crate"
reorder_imports = true
#group_imports = "StdExternalCrate"

# Modules
reorder_modules = true

# etc
#reorder_impl_items = true
use_try_shorthand = true
#wrap_comments = true
#normalize_comments = true
